FROM python:3.13.3-alpine AS build

WORKDIR /app

RUN apk add --no-cache curl

RUN curl -sSL https://install.python-poetry.org | python3 -

ENV PATH="/root/.local/bin:${PATH}"

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --no-root

FROM python:3.13.3-alpine

WORKDIR /app

COPY --from=build /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages
COPY --from=build /usr/local/bin /usr/local/bin
COPY --from=build /root/.local/bin/poetry /usr/local/bin/poetry

COPY . .

ENV SERVICE_NAME=menu
ENV DATABASE_SCHEMA=menu

EXPOSE 8001

