services:
  web-app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app/
    working_dir: /app
    env_file:
      - .env-dev
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - database
    networks:
      - my_app_network


  database:
    image: postgres:17-alpine
    container_name: postgresapp_fastapi
    env_file: 
      - .env-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_app_network


networks:
  my_app_network: 
    driver: bridge

volumes:
  postgres_data:
