services:
  web-app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app/
    working_dir: /app
    env_file:
      - .env-dev
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - my_app_network
  
  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my_app_network


  database:
    image: postgres:17-alpine
    container_name: postgresapp_fastapi
    environment:
      - POSTGRES_USER=projectuser
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=fast
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U projectuser -d fast"]
      interval: 5s
      timeout: 5s
      retries: 10


networks:
  my_app_network: 
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data: