"""create_order_tables

Revision ID: 166a060cf658
Revises: e5d8128b7da1
Create Date: 2024-03-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166a060cf658'
down_revision: Union[str, None] = 'e5d8128b7da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Создаем таблицу заказов
    op.create_table('orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('created', 'confirmed', 'preparing', 'ready', 'delivered', 'cancelled', name='order_status'), nullable=False),
        sa.Column('total_amount', sa.Integer(), nullable=False),
        sa.Column('delivery_address', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='orders'
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False, schema='orders')
    
    # Создаем таблицу позиций заказа
    op.create_table('order_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('dish_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('price_at_time', sa.Integer(), nullable=False),  # Цена на момент заказа
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['dish_id'], ['menu.dishes.id'], ),
        sa.ForeignKeyConstraint(['order_id'], ['orders.orders.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='orders'
    )
    op.create_index(op.f('ix_orders_order_items_id'), 'order_items', ['id'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_order_items_order_id'), 'order_items', ['order_id'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_order_items_dish_id'), 'order_items', ['dish_id'], unique=False, schema='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_items_dish_id'), table_name='order_items', schema='orders')
    op.drop_index(op.f('ix_orders_order_items_order_id'), table_name='order_items', schema='orders')
    op.drop_index(op.f('ix_orders_order_items_id'), table_name='order_items', schema='orders')
    op.drop_table('order_items', schema='orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders', schema='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders', schema='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders', schema='orders')
    op.drop_table('orders', schema='orders')
    # ### end Alembic commands ###
