"""Initial migration

Revision ID: 8d00f14a45d5
Revises: 
Create Date: 2025-05-28 23:36:29.213504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d00f14a45d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='menu'
    )
    op.create_index(op.f('ix_menu_categories_description'), 'categories', ['description'], unique=False, schema='menu')
    op.create_index(op.f('ix_menu_categories_id'), 'categories', ['id'], unique=False, schema='menu')
    op.create_index(op.f('ix_menu_categories_name'), 'categories', ['name'], unique=False, schema='menu')
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='menu'
    )
    op.create_index(op.f('ix_menu_tags_id'), 'tags', ['id'], unique=False, schema='menu')
    op.create_index(op.f('ix_menu_tags_name'), 'tags', ['name'], unique=False, schema='menu')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('number_phone', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_number_phone'), 'users', ['number_phone'], unique=True)
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['menu.categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='menu'
    )
    op.create_index(op.f('ix_menu_dishes_description'), 'dishes', ['description'], unique=False, schema='menu')
    op.create_index(op.f('ix_menu_dishes_id'), 'dishes', ['id'], unique=False, schema='menu')
    op.create_index(op.f('ix_menu_dishes_name'), 'dishes', ['name'], unique=False, schema='menu')
    op.create_index(op.f('ix_menu_dishes_price'), 'dishes', ['price'], unique=False, schema='menu')
    op.create_table('dish_tags',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['menu.dishes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['menu.tags.id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'tag_id'),
    schema='menu'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish_tags', schema='menu')
    op.drop_index(op.f('ix_menu_dishes_price'), table_name='dishes', schema='menu')
    op.drop_index(op.f('ix_menu_dishes_name'), table_name='dishes', schema='menu')
    op.drop_index(op.f('ix_menu_dishes_id'), table_name='dishes', schema='menu')
    op.drop_index(op.f('ix_menu_dishes_description'), table_name='dishes', schema='menu')
    op.drop_table('dishes', schema='menu')
    op.drop_index(op.f('ix_users_number_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_menu_tags_name'), table_name='tags', schema='menu')
    op.drop_index(op.f('ix_menu_tags_id'), table_name='tags', schema='menu')
    op.drop_table('tags', schema='menu')
    op.drop_index(op.f('ix_menu_categories_name'), table_name='categories', schema='menu')
    op.drop_index(op.f('ix_menu_categories_id'), table_name='categories', schema='menu')
    op.drop_index(op.f('ix_menu_categories_description'), table_name='categories', schema='menu')
    op.drop_table('categories', schema='menu')
    # ### end Alembic commands ###
